### PR TITLE
Move get token link position

### PR DESCRIPTION
**Pull request by memacius32**
- Moving GetTokenLink component position on Pool Cards.
- Reorder some files

### desktop:
Screen Shot 2022-04-04 at 17 33 06

### mobile:
Screen Shot 2022-04-04 at 17 34 13

### CODE REVIEW

**Comment by memacius32** [comment]
Also Disabled the link if user is staking. lmk if you think that's correct or not

**Comment by specialist0x** [comment]
What was the reason for moving this under deposit instead of the current location?

Might be nit-picky, but looks like there's a bit too much whitespace when the button isn't present:
image
wyt?

**Comment by memacius32** [comment]
> What was the reason for moving this under deposit instead of the current location?
> 
> Might be nit-picky, but looks like there's a bit too much whitespace when the button isn't present: image wyt?

It was a request from Metapool I think. @0xchain1  can add more info

I think I can make the link a little tinier maybe, and remove some space gap

**Comment by specialist0x** [comment]
@memacius32 Should we close this?

**Comment by memacius32** [comment]
Yeah, didn't get more feedback on this and we are changing farms cards so closing.

**Pull request closed without merging**
