### PR TITLE
Add ust and frax bridges

### PR DESCRIPTION
**Pull request by memacius32**
Screen Shot 2022-05-05 at 12 46 05

### CODE REVIEW

**Comment by rej156** [comment]
unsure about casing, will let you decide @specialist0x @0xchain1

**Comment by specialist0x** [comment]
Agreed -- can we change it to:

- Get Native FRAX
- Get Wormhole UST

**Comment by memacius32** [comment]
> Agreed -- can we change it to:
> 
> * Get Native FRAX
> * Get Wormhole UST

I am okay with this one, as this: 

> ya, i thnk we can make it upper case, also we can just make it less verbose? -- "Get FRAX", "Bridge UST"
 Can be a little confusing for users that have already frax and ust but in other versions, I think

If we all agree on that one I can change it

**Comment by specialist0x** [comment]
From [FRAX Documentation, there's bridged FRAX and Canonical/Native FRAX](https://docs.frax.finance/cross-chain/bridge#swapping-frax-fxs-and-peg-arbitrage-between-chains):

> If you bridge FRAX/FXS using any of the supported bridges (more to be added soon), you can swap the bridged token for native FRAX/FXS on that chain to farm/LP/hold etc.

Same deal for UST, we're offering two versions of it

What if we do `Get Native FRAX, Get Native UST` ?

**Review by specialist0x — APPROVED** [review]

**Pull request merged**
